//
// Created by Vishal Paudel on 05/04/24.
//

#include "raylib.h"

#ifndef FOURIER_SERIES_CONSTANTS_H
#define FOURIER_SERIES_CONSTANTS_H

#define MAX_FPS 60

#define SCREEN_HEIGHT 1000
#define SCREEN_WIDTH  1500

// Colors
#define CIRCUMFERENCE_COLOR LIGHTGRAY

#define BACKGROUND_COLOR BLACK
#define PEN_COLOR RAYWHITE
#define TEXT_COLOR LIGHTGRAY
#define TRACE_COLOR YELLOW

#endif //FOURIER_SERIES_CONSTANTS_H
